# Generated by Django 5.2.17 on 2026-10-10 03:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("images", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/%Y/%m/%d"),
        ),
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(max_length=200000),
        ),
    ]
